spring:
  application:
    name: smart-home-iot
  config:
    import: optional:file:.env[.properties]

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

server:
  port: 8080

  profiles:
    active: local


jwt:
  header: Authorization
  secret: ${JWT_SECRET_KEY}
  expiration: 36000