spring:
  application:
    name: smart-home-iot
  config:
    import: optional:file:.env[.properties]

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  kafka:
    bootstrap-servers: kafka:9092
    consumer:
      group-id: test-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

  profiles:
    active: local

server:
  port: 8080

jwt:
  header: Authorization
  secret: ${JWT_SECRET_KEY}
  expiration: 36000
