spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}

  mongodb:
    uri: ${SPRING_DATA_MONGODB_URI}

  redis:
    host: ${SPRING_REDIS_HOST}
    port: ${SPRING_REDIS_PORT}

  kafka:
    bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS}
#    consumer:
#      group-id: sensor-group
#      auto-offset-reset: earliest
#      enable-auto-commit: true
#      properties:
#        max.poll.records: 500
#        retry.backoff.ms: 5000
#    listener:
#      missing-topics-fatal: false
#    producer:
#      retries: 5
#      acks: all

jwt:
  secret: ${SPRING_JWT_SECRET_KEY}
